web_profiler_wdt:
    resource: '@WebProfilerBundle/Resources/config/Routing/wdt.xml'
    prefix: /_wdt

web_profiler_profiler:
    resource: '@WebProfilerBundle/Resources/config/Routing/profiler.xml'
    prefix: /_profiler
