api_news_index:
  path: /api/v1/news
  controller: App\Controller\NewsController::index
  methods:    GET|HEAD

api_news_show:
  path: /api/v1/news/{id}/show
  controller: App\Controller\NewsController::show
  methods:     GET|HEAD
  requirements:
           id: '\d+'

api_tags_index:
  path: /api/v1/tags
  controller: App\Controller\TagController::index
  methods: GET|HEAD

api_tags_show:
  path: /api/v1/tags/{id}/show
  controller: App\Controller\TagController::show
  methods: GET|HEAD
  requirements:
    id: '\d+'
